/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.aau;

import java.io.IOException;

import dk.aau.controllers.IntroController;
import dk.aau.controllers.PtCPRController;
import dk.aau.controllers.PtRootlayerController;
import dk.aau.controllers.PtSpg1Controller;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {
    private Stage primaryStage;
    private AnchorPane anchorpane;
    private BorderPane borderpane; 

    public static void main(String[] args) { launch(args);
        
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage; 
        this.primaryStage.setTitle("Projekt_ST5");
        // Set the application icon.
        this.primaryStage.getIcons()
                .add(new Image("/images/Logo.png"));
        showIntro();

    }

    public void showIntro() {
        try {
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getResource("/views/Intro.fxml"));
            anchorpane = (AnchorPane) loader.load();

            // Show the scene containing the root layout.
            Scene scene = new Scene(anchorpane);
            primaryStage.setScene(scene);

            primaryStage.show();
            IntroController controller = loader.getController();
            controller.setMainApp(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void showPtCPR() {
        try {
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getResource("/views/Pt_CPR.fxml"));
            anchorpane = (AnchorPane) loader.load();

            // Show the scene containing the root layout.
            Scene scene = new Scene(anchorpane);
            primaryStage.setScene(scene);

            primaryStage.show();
            PtCPRController controller = loader.getController();
            controller.setMainApp(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void showPtRootlayer(){
        try {
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getResource("/views/Pt_Rootlayer.fxml"));
            borderpane = (BorderPane) loader.load();

            // Show the scene containing the root layout.
            Scene scene = new Scene(borderpane);
            primaryStage.setScene(scene);

            primaryStage.show();
            PtRootlayerController controller = loader.getController();
            controller.setMainApp(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

        public void showPtSpg1() {
            try {
                // Load person overview.
                FXMLLoader loader = new FXMLLoader();
                loader.setLocation(App.class.getResource("/views/Pt_Spg1.fxml"));
                AnchorPane anchorpane = (AnchorPane) loader.load();
    
                // Set person overview into the center of root layout.
                borderpane.setCenter(anchorpane);
    
                // Give the controller access to the main app.
                PtSpg1Controller controller = loader.getController();
                controller.setMainApp(this);
    
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        public Stage getPrimaryStage() {
            return primaryStage;
        }

        public void showPtSlut() {
            try {
                // Load person overview.
                FXMLLoader loader = new FXMLLoader();
                loader.setLocation(App.class.getResource("/views/Pt_Slut.fxml"));
                AnchorPane anchorpane = (AnchorPane) loader.load();
    
                // Set person overview into the center of root layout.
                borderpane.setCenter(anchorpane);
    
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
